version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  springboot-app:
    build:
      context: .  # Assuming your Spring Boot project is in this directory
      dockerfile: Dockerfile
    container_name: springboot-app
    depends_on:
      - mongodb
    image: huantran2605/demo
    ports:
      - "8080:8080"  # Exposing the Spring Boot application port
    environment:
      - spring.data.mongodb.uri=mongodb://mongodb:27017/test  # Use the MongoDB service name
      - SPRING_PROFILES_ACTIVE=dev  # Set active profile to dev

volumes:
  mongo-data: